### ISSUE TITLE
Frontend and backend dockerfile get-poetry.py is deprecated

### ISSUE THREAD

**Issue by asd24684782** [ycc789741ycc/anime-recommender-service#1]
=> ERROR [backend:latest 3/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false  1.9s
------
 > [backend:latest 3/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false:
#0 1.828 Retrieving Poetry metadata
#0 1.828
#0 1.828 This installer is deprecated, and scheduled for removal from the Poetry repository on or after January 1, 2023.
#0 1.828 See https://github.com/python-poetry/poetry/issues/6377 for details.
#0 1.828
#0 1.828 You should migrate to https://install.python-poetry.org instead, which supports all versions of Poetry, and allows for `self update` of versions 1.1.7 or newer.
#0 1.828 Instructions are available at https://python-poetry.org/docs/#installation.
#0 1.828
#0 1.828 Without an explicit version, this installer will attempt to install the latest version of Poetry.
#0 1.828 This installer cannot install Poetry 1.2.0a1 or newer (and installs will be unable to `self update` to 1.2.0a1 or newer).
#0 1.828
#0 1.828 To continue to use this deprecated installer, you must specify an explicit version with --version <version> or POETRY_VERSION=<version>.
#0 1.828 Alternatively, if you wish to force this deprecated installer to use the latest installable release, set GET_POETRY_IGNORE_DEPRECATION=1.
#0 1.828
#0 1.828 Version 1.2.2 is not supported by this installer! Please specify a version prior to 1.2.0a1 to continue!

Maybe change `https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py` to ` https://install.python-poetry.org` will be ok.

**Comment by ycc789741ycc** [comment]
Thank for notifying the issue.
